<#
.SYNOPSIS
Configure the AgenticRelay App Service to connect to a Copilot Studio Agent.

.DESCRIPTION
This script reads configuration from config.json and updates the Azure App Service
configuration to point to the specified Copilot Studio agent.

.PARAMETER ResourceGroup
The Azure resource group containing the App Service.

.PARAMETER AppServiceName
The name of the Azure App Service running AgenticRelay.

.PARAMETER DirectConnectUrl
The Direct Connect URL from Copilot Studio (Native App channel connection string).

.PARAMETER AgentIdentityAppId
The Application (client) ID of the Agent Identity.

.PARAMETER AgentIdentitySecret
The client secret for the Agent Identity.

.PARAMETER TenantId
The Azure AD Tenant ID.

.EXAMPLE
.\Configure-CopilotStudioAgent.ps1 -SkipAgentIdentity

.EXAMPLE
.\Configure-CopilotStudioAgent.ps1 -DirectConnectUrl "https://..." -ResourceGroup "rg-agent365" -AppServiceName "app-agenticrelay-365"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$ResourceGroup,
    
    [Parameter(Mandatory = $false)]
    [string]$AppServiceName,
    
    [Parameter(Mandatory = $false)]
    [string]$DirectConnectUrl,
    
    [Parameter(Mandatory = $false)]
    [string]$AgentIdentityAppId,
    
    [Parameter(Mandatory = $false)]
    [string]$AgentIdentitySecret,
    
    [Parameter(Mandatory = $false)]
    [ValidatePattern('^[0-9a-fA-F-]{36}$')]
    [string]$TenantId,

    [Parameter(Mandatory = $false)]
    [switch]$SkipAgentIdentity
)

$ErrorActionPreference = "Stop"

# Colors
$InfoColor = "Cyan"
$SuccessColor = "Green"
$WarnColor = "Yellow"
$ErrorColor = "Red"

# Secrets file (gitignored)
$SecretsFile = ".env.local"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "▶ $Message" -ForegroundColor $InfoColor
    Write-Host ("-" * 60) -ForegroundColor Gray
}

function Test-AzureCli {
    try {
        $null = az --version 2>&1
        return $true
    }
    catch {
        return $false
    }
}

function Get-SecretsFromEnvFile {
    param([string]$FilePath)
    $secrets = @{}
    if (Test-Path $FilePath) {
        Get-Content $FilePath | ForEach-Object {
            if ($_ -match '^\s*([^#][^=]+)=(.*)$') {
                $key = $Matches[1].Trim()
                $value = $Matches[2].Trim().Trim('"').Trim("'")
                $secrets[$key] = $value
            }
        }
    }
    return $secrets
}

function Save-SecretsToEnvFile {
    param(
        [string]$FilePath,
        [hashtable]$Secrets
    )
    $content = "# Agent Identity Secrets (DO NOT COMMIT)`n"
    $content += "# Generated by Configure-CopilotStudioAgent.ps1`n"
    $content += "# Get these values from Copilot Studio portal after creating Agent Identity`n`n"
    foreach ($key in $Secrets.Keys) {
        $content += "$key=$($Secrets[$key])`n"
    }
    Set-Content -Path $FilePath -Value $content
}

# ============================================================================
# Prerequisites Check
# ============================================================================
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════════════════════════╗" -ForegroundColor $InfoColor
Write-Host "║           CONFIGURE COPILOT STUDIO AGENT CONNECTION                          ║" -ForegroundColor $InfoColor
Write-Host "╚══════════════════════════════════════════════════════════════════════════════╝" -ForegroundColor $InfoColor

Write-Step "Checking Prerequisites"

# Check Azure CLI
if (-not (Test-AzureCli)) {
    Write-Host "  [✗] Azure CLI (az) not found" -ForegroundColor $ErrorColor
    Write-Host "      Install it from: https://docs.microsoft.com/cli/azure/install-azure-cli" -ForegroundColor Gray
    exit 1
}
Write-Host "  [✓] Azure CLI (az) found" -ForegroundColor $SuccessColor

# ============================================================================
# Load Configuration from config.json
# ============================================================================
Write-Step "Loading Configuration"

$configPath = Join-Path $PSScriptRoot "config.json"
if (Test-Path $configPath) {
    $config = Get-Content $configPath | ConvertFrom-Json
    Write-Host "  [✓] Loaded config.json" -ForegroundColor $SuccessColor
    
    # Load values from config if not provided as parameters
    if ([string]::IsNullOrWhiteSpace($TenantId) -and $config.TenantId) {
        $TenantId = $config.TenantId
        Write-Host "    TenantId: $TenantId" -ForegroundColor Gray
    }
    if ([string]::IsNullOrWhiteSpace($ResourceGroup) -and $config.ResourceGroup) {
        $ResourceGroup = $config.ResourceGroup
        Write-Host "    ResourceGroup: $ResourceGroup" -ForegroundColor Gray
    }
    if ([string]::IsNullOrWhiteSpace($AppServiceName) -and $config.AppServiceName) {
        $AppServiceName = $config.AppServiceName
        Write-Host "    AppServiceName: $AppServiceName" -ForegroundColor Gray
    }
    if ([string]::IsNullOrWhiteSpace($DirectConnectUrl) -and $config.DirectConnectUrl) {
        $DirectConnectUrl = $config.DirectConnectUrl
        Write-Host "    DirectConnectUrl: $DirectConnectUrl" -ForegroundColor Gray
    }
    if ([string]::IsNullOrWhiteSpace($AgentIdentityAppId) -and $config.AgentIdentityAppId) {
        $AgentIdentityAppId = $config.AgentIdentityAppId
        Write-Host "    AgentIdentityAppId: $AgentIdentityAppId" -ForegroundColor Gray
    }
    if ([string]::IsNullOrWhiteSpace($AgentIdentitySecret) -and $config.AgentIdentitySecret) {
        $AgentIdentitySecret = $config.AgentIdentitySecret
        Write-Host "    AgentIdentitySecret: ********" -ForegroundColor Gray
    }
}
else {
    Write-Host "  [!] config.json not found at $configPath" -ForegroundColor $WarnColor
}

# Validate required values
$missingConfig = @()
if ([string]::IsNullOrWhiteSpace($TenantId)) { $missingConfig += "TenantId" }
if ([string]::IsNullOrWhiteSpace($ResourceGroup)) { $missingConfig += "ResourceGroup" }
if ([string]::IsNullOrWhiteSpace($AppServiceName)) { $missingConfig += "AppServiceName" }
if ([string]::IsNullOrWhiteSpace($DirectConnectUrl)) { $missingConfig += "DirectConnectUrl" }

if ($missingConfig.Count -gt 0) {
    Write-Host ""
    Write-Host "  [✗] Missing required configuration: $($missingConfig -join ', ')" -ForegroundColor $ErrorColor
    Write-Host "      Please add these values to config.json or pass them as parameters." -ForegroundColor Gray
    Write-Host ""
    Write-Host "      Example config.json:" -ForegroundColor Gray
    Write-Host '      {' -ForegroundColor DarkGray
    Write-Host '        "TenantId": "your-tenant-guid",' -ForegroundColor DarkGray
    Write-Host '        "ResourceGroup": "rg-agent365",' -ForegroundColor DarkGray
    Write-Host '        "AppServiceName": "app-agenticrelay-365",' -ForegroundColor DarkGray
    Write-Host '        "DirectConnectUrl": "https://...powerplatform.com/.../bots/contoso_agent/conversations?api-version=..."' -ForegroundColor DarkGray
    Write-Host '      }' -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "      To get DirectConnectUrl:" -ForegroundColor Gray
    Write-Host "      1. Go to Copilot Studio → Your Agent → Settings → Channels" -ForegroundColor Gray
    Write-Host "      2. Click 'Native App' channel" -ForegroundColor Gray
    Write-Host "      3. Copy the 'Connection String' URL" -ForegroundColor Gray
    exit 1
}

Write-Host "  [✓] Configuration validated" -ForegroundColor $SuccessColor

# ============================================================================
# Get Agent Identity Credentials (if not skipped)
# ============================================================================
if (-not $SkipAgentIdentity) {
    Write-Step "Agent Identity Configuration"
    
    # Try to load from .env.local file first
    $envFilePath = Join-Path $PSScriptRoot $SecretsFile
    if (Test-Path $envFilePath) {
        $secrets = Get-SecretsFromEnvFile -FilePath $envFilePath
        if ($secrets["AGENT_IDENTITY_APP_ID"] -and [string]::IsNullOrWhiteSpace($AgentIdentityAppId)) {
            $AgentIdentityAppId = $secrets["AGENT_IDENTITY_APP_ID"]
            Write-Host "  [✓] Loaded AgentIdentityAppId from $SecretsFile" -ForegroundColor $SuccessColor
        }
        if ($secrets["AGENT_IDENTITY_SECRET"] -and [string]::IsNullOrWhiteSpace($AgentIdentitySecret)) {
            $AgentIdentitySecret = $secrets["AGENT_IDENTITY_SECRET"]
            Write-Host "  [✓] Loaded AgentIdentitySecret from $SecretsFile" -ForegroundColor $SuccessColor
        }
    }
    
    # If still not set, prompt user
    if ([string]::IsNullOrWhiteSpace($AgentIdentityAppId)) {
        Write-Host ""
        Write-Host "  To get Agent Identity credentials:" -ForegroundColor Gray
        Write-Host "    1. Run createAgenticUser.ps1 to create Agent Identity" -ForegroundColor Gray
        Write-Host "    2. Copy the App ID and Secret from the output" -ForegroundColor Gray
        Write-Host ""
        $AgentIdentityAppId = Read-Host "  Agent Identity App ID"
    }
    
    if ([string]::IsNullOrWhiteSpace($AgentIdentitySecret)) {
        $secureSecret = Read-Host "  Agent Identity Secret" -AsSecureString
        $AgentIdentitySecret = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureSecret))
        
        # Offer to save to .env.local file
        Write-Host ""
        $saveToEnv = Read-Host "  Save credentials to $SecretsFile for next time? (y/n)"
        if ($saveToEnv -eq "y" -or $saveToEnv -eq "Y") {
            $secretsToSave = @{
                "AGENT_IDENTITY_APP_ID" = $AgentIdentityAppId
                "AGENT_IDENTITY_SECRET" = $AgentIdentitySecret
            }
            Save-SecretsToEnvFile -FilePath $envFilePath -Secrets $secretsToSave
            Write-Host "  [✓] Credentials saved to $SecretsFile" -ForegroundColor $SuccessColor
            Write-Host "  [!] Make sure $SecretsFile is in .gitignore!" -ForegroundColor $WarnColor
        }
    }
    
    # Validate Agent Identity values
    if ([string]::IsNullOrWhiteSpace($AgentIdentityAppId) -or [string]::IsNullOrWhiteSpace($AgentIdentitySecret)) {
        Write-Host "  [✗] Agent Identity App ID and Secret are required" -ForegroundColor $ErrorColor
        Write-Host "      Use -SkipAgentIdentity flag to skip this step" -ForegroundColor Gray
        exit 1
    }
    
    Write-Host "  Agent Identity App ID: $AgentIdentityAppId" -ForegroundColor Gray
    Write-Host "  Agent Identity Secret: ********" -ForegroundColor Gray
}

# ============================================================================
# Summary and Confirmation
# ============================================================================
Write-Step "Configuration Summary"

Write-Host "  App Service:          $AppServiceName" -ForegroundColor White
Write-Host "  Resource Group:       $ResourceGroup" -ForegroundColor White
Write-Host "  Direct Connect URL:   $DirectConnectUrl" -ForegroundColor White
if (-not $SkipAgentIdentity) {
    Write-Host "  Agent Identity:       $AgentIdentityAppId" -ForegroundColor White
}
Write-Host "  Tenant ID:            $TenantId" -ForegroundColor White
Write-Host ""

$confirm = Read-Host "Apply this configuration? (y/n)"
if ($confirm -ne "y" -and $confirm -ne "Y") {
    Write-Host "Configuration cancelled" -ForegroundColor $WarnColor
    exit 0
}

# ============================================================================
# Update App Service Configuration
# ============================================================================
Write-Step "Updating App Service Configuration"

$settings = @(
    "CopilotStudioAgent__DirectConnectUrl=$DirectConnectUrl",
    "TokenValidation__TenantId=$TenantId"
)

if (-not $SkipAgentIdentity) {
    $settings += "Connections__ServiceConnection__Settings__ClientId=$AgentIdentityAppId"
    $settings += "Connections__ServiceConnection__Settings__ClientSecret=$AgentIdentitySecret"
    $settings += "TokenValidation__Audiences__0=$AgentIdentityAppId"
}

Write-Host "  Applying settings to App Service..." -ForegroundColor Gray

$result = az webapp config appsettings set `
    --name $AppServiceName `
    --resource-group $ResourceGroup `
    --settings @settings 2>&1

if ($LASTEXITCODE -eq 0) {
    Write-Host "  [✓] App Service configuration updated" -ForegroundColor $SuccessColor
}
else {
    Write-Host "  [✗] Failed to update configuration" -ForegroundColor $ErrorColor
    Write-Host $result -ForegroundColor Red
    exit 1
}

# ============================================================================
# Restart App Service
# ============================================================================
Write-Step "Restarting App Service"

$restart = Read-Host "Restart the App Service now? (y/n)"
if ($restart -eq "y" -or $restart -eq "Y") {
    az webapp restart --name $AppServiceName --resource-group $ResourceGroup
    Write-Host "  [✓] App Service restarted" -ForegroundColor $SuccessColor
}
else {
    Write-Host "  Skipped restart. Remember to restart the App Service for changes to take effect." -ForegroundColor $WarnColor
}

# ============================================================================
# Done
# ============================================================================
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════════════════════════╗" -ForegroundColor $SuccessColor
Write-Host "║                    CONFIGURATION COMPLETED SUCCESSFULLY                      ║" -ForegroundColor $SuccessColor
Write-Host "╚══════════════════════════════════════════════════════════════════════════════╝" -ForegroundColor $SuccessColor
Write-Host ""
Write-Host "  Your AgenticRelay is now configured to connect to:" -ForegroundColor White
Write-Host "    Direct Connect URL: $DirectConnectUrl" -ForegroundColor $SuccessColor
Write-Host "    App Service URL:    https://$AppServiceName.azurewebsites.net" -ForegroundColor $SuccessColor
Write-Host ""
Write-Host "  To verify the app is running:" -ForegroundColor Gray
Write-Host "    Invoke-WebRequest -Uri 'https://$AppServiceName.azurewebsites.net' -UseBasicParsing" -ForegroundColor Gray
Write-Host ""
